name: log
version: 0.0.6
author: Andrew Peterson <andrewwaynepeterson@gmail.com>
description: A logging tool for dart CLI applications.
homepage: http://github.com/andruj/log
environment:
  sdk: ">=1.8.0"
dependencies:
  dye: ^0.0.1
